image: gradle:jdk8

stages:
  - build-test
  - package-upload

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

# Global rules for when to create a pipeline https://gitlab.com/help/ci/yaml/README.md#workflowrules
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: "$CI_COMMIT_BRANCH =~ /^release_/"
      when: never
    - when: always

test-and-build-knsq:
  stage: build-test
  services:
    - docker:19.03-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_VERSION: "19.03.13"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  tags:
    - docker-in-docker
  script:
    - curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz
    - tar xzvf docker-$DOCKER_VERSION.tgz --strip 1
      -C /usr/local/bin docker/docker
    - gradle test

publish-knsq:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "release"'
      when: on_success
  stage: package-upload
  artifacts:
    expire_in: 1 hour
    paths:
      - build/libs/*.jar
  dependencies:
    - test-and-build-knsq
  script:
    - gradle publish

pages:
  rules:
    - if: '$CI_COMMIT_BRANCH == "release"'
      when: on_success
  stage: package-upload
  dependencies:
    - test-and-build-knsq
  script:
    - gradle dokkaHtml dokkaJavadoc
    - mkdir public && mv build/dokka public
  artifacts:
    paths:
      - public